### ISSUE TITLE
how can I see Distri.js in action on my console

### ISSUE THREAD

**Issue by doussa91** [Flarp/Distri-JS#8]
I'm a student and I have a project in distributed computing and I would like to use Distri.js. I have installed it in my computer but before starting the project I tried to executed the collatz example but I don't know how to see it in my console and how getting the result. So I would like to have more information about and which command can I use for checking it in my console.
I'm hoping to have an answer soon.

Ps: excuse for my mistake I'm not a English man

**Comment by ethan-dorta** [comment]
The current tutorial is out of date, and I was working on updating it before I came down with some really bad virus.

The master branch is out of date as well, so please use the dev branch. (For both Distri.js and Distri-Node). 

Also, you made no mention of using Distri-Node. Could you explain your current setup? Distri-Node is required for Distri.js. (I can't really answer anything else until I know how you're going about things)

**Comment by ethan-dorta** [comment]
Also, please note volunteer computing is a subset of distributed computing. I'm not sure this library is what you're looking for, so check with your profressor to see if it is okay.

**Comment by doussa91** [comment]
My project is to set up a website and if someone visite the website, the program ask him if he can be a volunteer for computing. At the end the program get back every result.
I have downloaded my current setup on "Distri.js.org" and before installing it I installed Node.js first. Then I used a npm command to install it. When I use node commande on javascript files from collatz example everything is ok and when I lauch the html file (click on the button) the windows pop appear for adding a server.But then I can't see what's going on.

**Comment by ethan-dorta** [comment]
You aren't connected to the server yet. Click "Add Server" (the yellow button on the menu) and enter `localhost:8081`, then hit Enter. If you don't hit enter nothing will happen. Try that and tell me what happens.

**Comment by doussa91** [comment]
I have add the server but nothing heppen ,a pop up has just gone. which command can I use on the console to see what happen

**Comment by ethan-dorta** [comment]
Did you make sure to hit enter? To bring back the menu, call `Distri.settings`.

**Comment by doussa91** [comment]
yes I hit enter! can you tell what happen when it's work and how to see that please

**Comment by doussa91** [comment]
yes I hit enter! can you tell me what happen when it's work and how to see that please

**Comment by ethan-dorta** [comment]
If you put in everything correctly, hit "Finish" and it should work. Again, if you are not, _use the dev branch_.

**Comment by doussa91** [comment]
I have add the server and at the end I hit finish but whe I try to go on "http://localhost:8080/" this sentence "Upgrade Required"  is display on

**Comment by ethan-dorta** [comment]
Upgrade Required means you are trying to access a WebSocket through HTTP. Distri.js needs to be in an HTML file. So grab a copy of Distri.js (by cloning the repo and running webpack), and create an HTML file with these contents.

```html
<body>

</body>
<script src="path/to/distri.min.js"></script>
```

And now I'm confused. Please send me a screenshot of what you're seeing.

**Comment by doussa91** [comment]
this is a screeshot that you asked

2017-02-17 22:03 GMT+01:00 Flarp <notifications@github.com>:

**Comment by ethan-dorta** [comment]
A screenshot of your Distri console and website, sorry.

**Comment by doussa91** [comment]
my console

2017-02-18 14:11 GMT+01:00 Flarp <notifications@github.com>:

**Comment by ethan-dorta** [comment]
Here, I am mega confused on what's going on, so I recorded a video on how to do it.

https://youtu.be/Hpk4VHfLlyw

I hope this helps. I'll leave this issue open for further questions.

**Comment by doussa91** [comment]
thank you very much,it's of a great help

**Comment by ethan-dorta** [comment]
Actually, to clean up issues, since it seems it's all resolved, I'm going to close it, but feel free to re open and ask anything else at any other time.

**Comment by doussa91** [comment]
ok thank you!

**Comment by ethan-dorta** [comment]
Also, I would like to know how everything turns out, so do tell. Good luck!

**Comment by doussa91** [comment]
ok when I'm done I will let you Know
